Mamma_Pasta/Models/Cliente.cs
namespace Mamma_Pasta.Models
{
    public class Cliente
    {
        public int Id { get; set; }
        public string? Nombre { get; set; }
        public int? Telefono { get; set; }
        public string? Direccion { get; set; }
        public int TipoDePagoId { get; set; }
        public TipoDePago? TiposDePago { get; set; }
        public bool Activo { get; set; } = true;
    }
}

Mamma_Pasta/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Mamma_Pasta.Data;
using Mamma_Pasta.Models;
using Mamma_Pasta.Migrations;
using Microsoft.AspNetCore.Authorization;

namespace Mamma_Pasta.Controllers
{

    public class ClientesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ClientesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Clientes
        public async Task<IActionResult> Index()
        {
            var clientes = _context.Clientes
                .Include(c => c.TiposDePago)
                .Where(v => v.Activo)
                .AsQueryable();
            return View(clientes);
        }
        public async Task<IActionResult> ClientesEliminados()
        {
            var clientes = await _context.Clientes
                .Where(v => !v.Activo)
                .OrderBy(v => v.Nombre)
                .ToListAsync();

            return View(clientes);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RestaurarCliente(int id)
        {
            var cliente = await _context.Clientes.FindAsync(id);
            if (cliente == null)
            {
                return NotFound();
            }

            // Restaurar la venta cambiando Activo a true
            cliente.Activo = true;
            _context.Clientes.Update(cliente);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(ClientesEliminados));
        }

        // GET: Clientes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes
                .Include(c => c.TiposDePago)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // GET: Clientes/Create
        public IActionResult Create()
        {
            ViewData["TipoDePagoId"] = new SelectList(_context.TiposDePago, "Id", "Tipo");
            return View();
        }

        // POST: Clientes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Apellido,Telefono,Direccion,TipoDePagoId")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cliente);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["TipoDePagoId"] = new SelectList(_context.TiposDePago, "Id", "Tipo", cliente.TipoDePagoId);
            return View(cliente);
        }

        // GET: Clientes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes.FindAsync(id);
            if (cliente == null)
            {
                return NotFound();
            }
            ViewData["TipoDePagoId"] = new SelectList(_context.TiposDePago, "Id", "Tipo", cliente.TipoDePagoId);
            return View(cliente);
        }

        // POST: Clientes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Apellido,Telefono,Direccion,TipoDePagoId")] Cliente cliente)
        {
            if (id != cliente.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cliente);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClienteExists(cliente.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["TipoDePagoId"] = new SelectList(_context.TiposDePago, "Id", "Tipo", cliente.TipoDePagoId);
            return View(cliente);
        }

        // GET: Clientes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes
                .Include(c => c.TiposDePago)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // POST: Clientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cliente = await _context.Clientes.FindAsync(id);
            if (cliente == null)
            {
                return NotFound();
            }
            cliente.Activo = false;
            _context.Clientes.Update(cliente);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        private bool ClienteExists(int id)
        {
            return _context.Clientes.Any(e => e.Id == id);
        }
    }
}

Mamma_Pasta/Controllers/TipoDePagosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Mamma_Pasta.Data;
using Mamma_Pasta.Models;
using Microsoft.AspNetCore.Authorization;

namespace Mamma_Pasta.Controllers
{

    public class TipoDePagosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TipoDePagosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: TipoDePagos
        public async Task<IActionResult> Index()
        {
            return View(await _context.TiposDePago.ToListAsync());
        }

        // GET: TipoDePagos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tipoDePago = await _context.TiposDePago
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tipoDePago == null)
            {
                return NotFound();
            }

            return View(tipoDePago);
        }

        // GET: TipoDePagos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TipoDePagos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Tipo")] TipoDePago tipoDePago)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tipoDePago);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tipoDePago);
        }

        // GET: TipoDePagos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tipoDePago = await _context.TiposDePago.FindAsync(id);
            if (tipoDePago == null)
            {
                return NotFound();
            }
            return View(tipoDePago);
        }

        // POST: TipoDePagos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Tipo")] TipoDePago tipoDePago)
        {
            if (id != tipoDePago.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tipoDePago);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TipoDePagoExists(tipoDePago.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tipoDePago);
        }

        // GET: TipoDePagos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tipoDePago = await _context.TiposDePago
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tipoDePago == null)
            {
                return NotFound();
            }

            return View(tipoDePago);
        }

        // POST: TipoDePagos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tipoDePago = await _context.TiposDePago.FindAsync(id);
            if (tipoDePago != null)
            {
                _context.TiposDePago.Remove(tipoDePago);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TipoDePagoExists(int id)
        {
            return _context.TiposDePago.Any(e => e.Id == id);
        }
    }
}

Mamma_Pasta/Views/Clientes/ClientesEliminados.cshtml
@model List<Cliente>

<h2>Clientes Eliminados</h2>

<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Telefono</th>
            <th>Direccion</th>
            <th>Tipo de Pago</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var cliente in Model)
        {
            <tr>
                <td>@cliente.Id</td>
                <td>@cliente.Nombre</td>
                <td>@cliente.Telefono</td>
                <th>@cliente.Direccion</th>
                <th>@cliente.TiposDePago?.Tipo</th>
                <td>
                    <div class="d-flex gap-2">
                        <a asp-action="Details" asp-route-id="@cliente.Id" class="btn btn-warning">Detalles</a> |
                        <form asp-action="RestaurarCliente" asp-route-id="@cliente.Id" method="post">
                            <button type="submit" class="btn btn-success">Restaurar</button>
                        </form>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>
<div>
    <a asp-action="Index" class="btn btn-warning" style="margin-top:50px">Volver a la lista</a>
</div>

Mamma_Pasta/Views/Clientes/Create.cshtml
@model Mamma_Pasta.Models.Cliente

@{
    ViewData["Title"] = "Create";
}

<h1>Crear</h1>
<br />
<h4>Cliente</h4>
<hr />
<div class="container">
    <div class="row d-flex justify-content-center">
        <div class="col-md-6">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="row mb-3">
                    <label asp-for="Nombre" class="col-sm-3 col-form-label">Nombre:</label>
                    <div class="col-sm-9">
                        <input asp-for="Nombre" class="form-control" />
                        <span asp-validation-for="Nombre" class="text-danger"></span>
                    </div>
                </div>
                <div class="row mb-3">
                    <label asp-for="Telefono" class="col-sm-3 col-form-label">Telefono:</label>
                    <div class="col-sm-9">
                        <input asp-for="Telefono" class="form-control" />
                        <span asp-validation-for="Telefono" class="text-danger"></span>
                    </div>
                </div>
                <div class="row mb-3">
                    <label asp-for="Direccion" class="col-sm-3 col-form-label">Direccion:</label>
                    <div class="col-sm-9">
                        <input asp-for="Direccion" class="form-control" />
                        <span asp-validation-for="Direccion" class="text-danger"></span>
                    </div>
                </div>
                <div class="row mb-3">
                    <label asp-for="TipoDePagoId" class="col-sm-3 col-form-label">Tipo:</label>
                    <div class="col-sm-9">
                        <select asp-for="TipoDePagoId" class="form-control" asp-items="ViewBag.TipoDePagoId"></select>
                    </div>
                </div>
                <div class="d-grid">
                    <input type="submit" value="Crear" class="btn btn-warning btn-block" />
                </div>
            </form>
        </div>
    </div>
</div>


<div>
    <a asp-action="Index" class="btn btn-warning">Volver a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Mamma_Pasta/Views/Clientes/Delete.cshtml
@model Mamma_Pasta.Models.Cliente

@{
    ViewData["Title"] = "Delete";
}

<h1>Borrar</h1>

<h3>¿Esta seguro de querer borrar esto?</h3>
<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefono)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Direccion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TiposDePago)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TiposDePago.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Borrar" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-warning">Volver a la lista</a>
    </form>
</div>

Mamma_Pasta/Views/Clientes/Details.cshtml
@model Mamma_Pasta.Models.Cliente

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles</h1>

<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefono)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Direccion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TiposDePago)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TiposDePago.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-warning">Editar</a> |
    <a asp-action="Index" class="btn btn-warning">Volver a la lista</a>
</div>

Mamma_Pasta/Views/Clientes/Edit.cshtml
@model Mamma_Pasta.Models.Cliente

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>
<br />
<h4>Cliente</h4>
<hr />
<div class="container">
    <div class="row d-flex justify-content-center">
        <div class="col-md-6">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <div class="row mb-3">
                    <label asp-for="Nombre" class="col-sm-3 col-form-label">Nombre:</label>
                    <div class="col-sm-9">
                        <input asp-for="Nombre" class="form-control" />
                        <span asp-validation-for="Nombre" class="text-danger"></span>
                    </div>
                </div>
                <div class="row mb-3">
                    <label asp-for="Telefono" class="col-sm-3 col-form-label">Telefono:</label>
                    <div class="col-sm-9">
                        <input asp-for="Telefono" class="form-control" />
                        <span asp-validation-for="Telefono" class="text-danger"></span>
                    </div>
                </div>
                <div class="row mb-3">
                    <label asp-for="Direccion" class="col-sm-3 col-form-label">Direccion:</label>
                    <div class="col-sm-9">
                        <input asp-for="Direccion" class="form-control" />
                        <span asp-validation-for="Direccion" class="text-danger"></span>
                    </div>
                </div>
                <div class="row mb-3">
                    <label asp-for="TipoDePagoId" class="col-sm-3 col-form-label">Tipo:</label>
                    <div class="col-sm-9">
                        <select asp-for="TipoDePagoId" class="form-control" asp-items="ViewBag.TipoDePagoId"></select>
                    </div>
                </div>
                <div class="d-grid">
                    <input type="submit" value="Guardar" class="btn btn-warning btn-block" />
                </div>
            </form>
        </div>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-warning">Volver a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Mamma_Pasta/Views/Clientes/Index.cshtml
@model IEnumerable<Mamma_Pasta.Models.Cliente>

@{
    ViewData["Title"] = "Index";
}

<h1>Clientes</h1>

<div class="d-flex justify-content-between align-items-center mb-3">
    <div>
        <a asp-action="Create" class="btn btn-warning" title="Alt + E">Nuevo Cliente</a>
        <a class="btn btn-warning" asp-area="" asp-controller="TipoDePagos" asp-action="Index">Tipos de Pago</a>
    </div>
    <div>
        <a asp-controller="Clientes" asp-action="ClientesEliminados" class="btn btn-secondary">Clientes Eliminados</a>
    </div>
    
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefono)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Direccion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TiposDePago.Tipo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Telefono)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Direccion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TiposDePago.Tipo)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning">Editar</a> |
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-warning">Detalles</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Borrar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<script>
    document.addEventListener('keydown', function (event) {
        if (event.altKey && event.key === 'e') {
            event.preventDefault(); // Evita la acción predeterminada del navegador
            window.location.href = '@Url.Action("Create", "Clientes")'; // Redirige al método Create del controlador Ventas
        }
    });
</script>