Mamma_Pasta/Models/Producto.cs
namespace Mamma_Pasta.Models
{
    public class Producto
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string? Descripcion { get; set; }
        public int TipoProductoId { get; set; }
        public decimal Precio { get; set; }
        public string? Imagen { get; set; }
        public TipoProducto? tipoProductos { get; set; }
        public bool Activo { get; set; } = true;
    }
}

Mamma_Pasta/Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Mamma_Pasta.Data;
using Mamma_Pasta.Models;
using Microsoft.AspNetCore.Authorization;
using AspNetCoreGeneratedDocument;
using Mamma_Pasta.Migrations;

namespace Mamma_Pasta.Controllers
{

    public class ProductosController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _env;

        public ProductosController(ApplicationDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }
      
        // GET: Productos
        public async Task<IActionResult> Index(string BusqNombre, int? TipoProductoId, int pagina = 1)
        {

            Paginador paginador = new Paginador
            {
                paginaActual = pagina,
                cantRegistrosPagina = 10,
            };

            var producto = _context.Productos
                .Include(e => e.tipoProductos)
                .Select(e => e)
                .Where(e => e.Activo)
                .AsQueryable();
            var lista = await _context.Productos
                .Where(e => e.Activo) // Solo productos activos
                .Include(e => e.tipoProductos)
                .ToListAsync();
            var tipos = await _context.TiposProductos.ToListAsync();
            foreach (var item in lista)
            {
                item.tipoProductos = tipos.Find(e => e.Id == item.TipoProductoId);
            }

            if (!string.IsNullOrEmpty(BusqNombre))
            {
                producto = producto.Where(e => e.Nombre.Contains(BusqNombre));
                paginador.filtros.Add("BusqNombre", BusqNombre);
            }
            if (TipoProductoId.HasValue)
            {
                producto = producto.Where(e => e.TipoProductoId == TipoProductoId);
                paginador.filtros.Add("TipoProductoId", TipoProductoId.ToString());
            }

            producto = producto.OrderBy(e => e.Nombre);

            paginador.cantRegistros = producto.Count();

            producto = producto
                .Skip(paginador.cantRegistrosPagina * (pagina - 1))
                .Take(paginador.cantRegistrosPagina);

            vmProductos modelo = new vmProductos
            {
                ListProductos = await producto.ToListAsync(),
                ListTiposProd = new SelectList(_context.TiposProductos, "Id", "Tipo"),
                BusqNombre = BusqNombre,
                TipoProductoId = TipoProductoId,
                paginadorVM = paginador
            };


            ViewData["TipoProductoId"] = new SelectList(_context.TiposProductos, "Id", "Tipo", TipoProductoId);
            return View(modelo);
        }
        public async Task<IActionResult> ProductosEliminados()
        {
            var productos = await _context.Productos
                .Where(v => !v.Activo) // Filtrar solo las ventas eliminadas
                .Include(v => v.tipoProductos)
                .ToListAsync();

            return View(productos);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RestaurarProducto(int id)
        {
            var producto = await _context.Productos.FindAsync(id);
            if (producto == null)
            {
                return NotFound();
            }

            // Restaurar la venta cambiando Activo a true
            producto.Activo = true;
            _context.Productos.Update(producto);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(ProductosEliminados));
        }


        public async Task<IActionResult> Import()
        {
            var archivos = HttpContext.Request.Form.Files;
            if (archivos != null && archivos.Count > 0)
            {
                var archivo = archivos[0];
                if (archivo.Length > 0)
                {
                    var pathDestino = Path.Combine(_env.WebRootPath, "Importaciones");
                    var archivoDestino = Guid.NewGuid().ToString().Replace("-", "");
                    archivoDestino += Path.GetExtension(archivo.FileName);
                    var rutaDestino = Path.Combine(pathDestino, archivoDestino);

                    using (var filestream = new FileStream(rutaDestino, FileMode.Create))
                    {
                        archivo.CopyTo(filestream);
                    }

                    using (var file = new FileStream(rutaDestino, FileMode.Open))
                    {
                        List<string> reng = new List<string>();
                        List<Producto> ProductosArch = new List<Producto>();

                        StreamReader fileContent = new StreamReader(file, System.Text.Encoding.Default);
                        do
                        {
                            reng.Add(fileContent.ReadLine());
                        }
                        while (!fileContent.EndOfStream);

                        if (reng.Count() > 0)
                        {
                            foreach (var row in reng)
                            {
                                string[] data = row.Split(';');
                                if (data.Length == 5)
                                {
                                    Producto Productos = new Producto();
                                    Productos.Nombre = data[0].Trim();
                                    Productos.Descripcion = data[1].Trim();
                                    Productos.TipoProductoId = int.Parse(data[2].Trim());
                                    Productos.Precio = int.Parse(data[3].Trim());
                                    ProductosArch.Add(Productos);
                                }

                            }
                            if (ProductosArch.Count() > 0)
                            {
                                _context.AddRange(ProductosArch);
                                await _context.SaveChangesAsync();
                            }
                        }
                    }
                }
            }
            var producto = _context.Productos.Include(e => e.tipoProductos);
            return RedirectToAction("Index");
        }

        // GET: Productos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.Productos
                .Include(e => e.tipoProductos)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (producto == null)
            {
                var lista = await _context.Productos.ToListAsync();
                var tipos = await _context.TiposProductos.ToListAsync();
                foreach (var item in lista)
                {
                    item.tipoProductos = tipos.Find(e => e.Id == item.TipoProductoId);
                }
                return View(lista);
                return NotFound();
            }

            return View(producto);
        }

        // GET: Productos/Create
        public IActionResult Create()
        {
            ViewData["TipoProductoId"] = new SelectList(_context.TiposProductos, "Id", "Tipo");
            return View();
        }

        // POST: Productos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Descripcion,TipoProductoId,Precio,Imagen")] Producto producto)
        {
            if (ModelState.IsValid)
            {
                var archivos = HttpContext.Request.Form.Files;
                if (archivos != null && archivos.Count > 0)
                {
                    var archivoImagen = archivos[0];
                    if (archivoImagen.Length > 0)
                    {
                        var rutaDestino = Path.Combine(_env.WebRootPath, "Imagenes", "Productos");
                        var extension = Path.GetExtension(archivoImagen.FileName);
                        var archivoDestino = producto.Nombre.ToString() + extension;
                        //var archivoDestino = Guid.NewGuid().ToString().Replace("-", "") + extension; //NOMBRE ALEATORIO

                        using (var filestream = new FileStream(Path.Combine(rutaDestino, archivoDestino), FileMode.Create))
                        {
                            archivoImagen.CopyTo(filestream);
                            producto.Imagen = archivoDestino;
                        }
                    }
                }

                _context.Add(producto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["TipoProductoId"] = new SelectList(_context.TiposProductos, "Id", "Tipo", producto.TipoProductoId);
            return View(producto);
        }

        // GET: Productos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.Productos.FindAsync(id);
            if (producto == null)
            {
                return NotFound();
            }
            ViewData["TipoProductoId"] = new SelectList(_context.TiposProductos, "Id", "Tipo", producto.TipoProductoId);
            return View(producto);
        }

        // POST: Productos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.

Mamma_Pasta/Controllers/TipoProductosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Mamma_Pasta.Data;
using Mamma_Pasta.Models;
using Microsoft.AspNetCore.Authorization;

namespace Mamma_Pasta.Controllers
{

    public class TipoProductosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TipoProductosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: TipoProductos
        public async Task<IActionResult> Index()
        {
            return View(await _context.TiposProductos.ToListAsync());
        }

        // GET: TipoProductos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tipoProducto = await _context.TiposProductos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tipoProducto == null)
            {
                return NotFound();
            }

            return View(tipoProducto);
        }

        // GET: TipoProductos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TipoProductos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Tipo")] TipoProducto tipoProducto)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tipoProducto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tipoProducto);
        }

        // GET: TipoProductos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tipoProducto = await _context.TiposProductos.FindAsync(id);
            if (tipoProducto == null)
            {
                return NotFound();
            }
            return View(tipoProducto);
        }

        // POST: TipoProductos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Tipo")] TipoProducto tipoProducto)
        {
            if (id != tipoProducto.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tipoProducto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TipoProductoExists(tipoProducto.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tipoProducto);
        }

        // GET: TipoProductos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tipoProducto = await _context.TiposProductos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tipoProducto == null)
            {
                return NotFound();
            }

            return View(tipoProducto);
        }

        // POST: TipoProductos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tipoProducto = await _context.TiposProductos.FindAsync(id);
            if (tipoProducto != null)
            {
                _context.TiposProductos.Remove(tipoProducto);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TipoProductoExists(int id)
        {
            return _context.TiposProductos.Any(e => e.Id == id);
        }
    }
}

Mamma_Pasta/Views/Productos/Create.cshtml
@model Mamma_Pasta.Models.Producto

@{
    ViewData["Title"] = "Create";
}

<h1>Crear</h1>
<br />
<h4>Producto</h4>
<hr />


<div class="container">
    <div class="row d-flex justify-content-center">
        <div class="col-md-6">
            <form asp-action="Create" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="row mb-3">
                    <label asp-for="Nombre" class="col-sm-3 col-form-label">Nombre:</label>
                    <div class="col-sm-9">
                        <input asp-for="Nombre" class="form-control" />
                        <span asp-validation-for="Nombre" class="text-danger"></span>
                    </div>
                </div>

                <div class="row mb-3">
                    <label asp-for="Descripcion" class="col-sm-3 col-form-label">Descripción:</label>
                    <div class="col-sm-9">
                        <input asp-for="Descripcion" class="form-control" />
                        <span asp-validation-for="Descripcion" class="text-danger"></span>
                    </div>
                </div>

                <div class="row mb-3">
                    <label asp-for="TipoProductoId" class="col-sm-3 col-form-label">Tipo:</label>
                    <div class="col-sm-9">
                        <select asp-for="TipoProductoId" class="form-control" asp-items="ViewBag.TipoProductoId"></select>
                    </div>
                </div>

                <div class="row mb-3">
                    <label asp-for="Precio" class="col-sm-3 col-form-label">Precio:</label>
                    <div class="col-sm-9">
                        <input asp-for="Precio" class="form-control" />
                        <span asp-validation-for="Precio" class="text-danger"></span>
                    </div>
                </div>

                <div class="row mb-3">
                    <label asp-for="Imagen" class="col-sm-3 col-form-label">Imagen:</label>
                    <div class="col-sm-9">
                        <input type="file" id="Imagen" name="Imagen" class="form-control" />
                    </div>
                </div>

                <div class="d-grid">
                    <button type="submit" class="btn btn-warning btn-block">Crear</button>
                </div>
            </form>

            <hr class="my-4">


            <form asp-action="Import" enctype="multipart/form-data">
                <div class="row mb-3">
                    <label class="col-sm-4 col-form-label">Importar archivo:</label>
                    <div class="col-sm-8">
                        <input type="file" name="arch" id="arch" class="form-control" required />
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-8 offset-sm-4">
                        <input type="submit" value="Importar" class="btn btn-warning" />
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-warning">Volver a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Mamma_Pasta/Views/Productos/Delete.cshtml
@model Mamma_Pasta.Models.Producto

@{
    ViewData["Title"] = "Delete";
}

<h1>Borrar</h1>

<h3>¿Esta seguro de querer borrar esto?</h3>
<br />
<h4>Producto</h4>
<div class="d-flex">
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.tipoProductos.Tipo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.tipoProductos.Tipo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
    </dl>
    <input type="hidden" asp-for="Imagen" />
    @if (!string.IsNullOrEmpty(Model.Imagen))
    {
        <div class="me-3">
            <img src="~/Imagenes/Productos/@Model.Imagen" style="max-width:300px" />
        </div>
    }
</div>
<div style="margin-top: 15px">
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Borrar" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-warning">Volver a la lista</a>
    </form>
</div>

Mamma_Pasta/Views/Productos/Details.cshtml
@model Mamma_Pasta.Models.Producto

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles</h1>

<br />
<h4>Producto</h4>
<div class="d-flex">
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.tipoProductos.Tipo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.tipoProductos.Tipo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
    </dl>

    <input type="hidden" asp-for="Imagen" />
    @if (!string.IsNullOrEmpty(Model.Imagen))
    {
        <div class="me-3">
            <img src="~/Imagenes/Productos/@Model.Imagen" style="max-width:300px" />
        </div>
    }

</div>
<div style="margin-top: 15px">
    <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-warning">Editar</a> |
    <a asp-action="Index" class="btn btn-warning">Volver a la lista</a>
</div>

Mamma_Pasta/Views/Productos/Edit.cshtml
@model Mamma_Pasta.Models.Producto

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>
<br />
<h4>Producto</h4>
<hr />
<div class="container">
    <div class="row d-flex justify-content-center">
        <div class="col-md-6">
            <form asp-action="Edit" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <div class="row mb-3">
                    <label asp-for="Nombre" class="col-sm-3 col-form-label">Nombre:</label>
                    <div class="col-sm-9">
                        <input asp-for="Nombre" class="form-control" />
                        <span asp-validation-for="Nombre" class="text-danger"></span>
                    </div>
                </div>

                <div class="row mb-3">
                    <label asp-for="Descripcion" class="col-sm-3 col-form-label">Descripción:</label>
                    <div class="col-sm-9">
                        <input asp-for="Descripcion" class="form-control" />
                        <span asp-validation-for="Descripcion" class="text-danger"></span>
                    </div>
                </div>

                <div class="row mb-3">
                    <label asp-for="TipoProductoId" class="col-sm-3 col-form-label">Tipo:</label>
                    <div class="col-sm-9">
                        <select asp-for="TipoProductoId" class="form-control" asp-items="ViewBag.TipoProductoId"></select>
                    </div>
                </div>

                <div class="row mb-3">
                    <label asp-for="Precio" class="col-sm-3 col-form-label">Precio:</label>
                    <div class="col-sm-9">
                        <input asp-for="Precio" class="form-control" />
                        <span asp-validation-for="Precio" class="text-danger"></span>
                    </div>
                </div>

                <div class="row mb-3">
                    <label asp-for="Imagen" class="col-sm-3 col-form-label">Imagen:</label>
                    <div class="col-sm-9">
                        <input type="file" id="Imagen" name="Imagen" class="form-control" />
                        @if (!string.IsNullOrEmpty(Model.Imagen))
                        {
                            <div class="mt-2">
                                <img src="~/Imagenes/Productos/@Model.Imagen" alt="Imagen del producto" class="img-thumbnail" style="max-width: 150px;" />
                            </div>
                        }
                    </div>
                </div>

                <div class="d-grid">
                    <button type="submit" class="btn btn-warning btn-block">Guardar</button>
                </div>
            </form>
        </div>
    </div>
</div>


<div>
    <a asp-action="Index" class="btn btn-warning">Volver a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Mamma_Pasta/Views/Productos/Index.cshtml
@model Mamma_Pasta.Models.vmProductos

@{
    ViewData["Title"] = "Index";
}

<h1>Productos</h1>

<div class="d-flex justify-content-between align-items-center mb-3 flex-wrap">
    <div>
        <a asp-action="Create" class="btn btn-warning" title="Alt + E">Nuevo Producto</a>
        <a class="btn btn-warning" asp-area="" asp-controller="TipoProductos" asp-action="Index">Tipo de productos</a>
    </div>
    <form asp-action="Index" method="get" class="d-flex gap-2">
        <select name="TipoProductoId" asp-items="ViewBag.TipoProductoId" class="form-select" onchange="this.form.submit()">
            <option value="" selected="@(string.IsNullOrEmpty(ViewBag.TipoProductoId?.ToString()) ? "selected" : null)">Todos los productos</option>
        </select>
        <input placeholder="Filtrar por Nombre" type="text" name="BusqNombre" class="form-control"/>
        <input type="submit" value="Filtrar" class="btn btn-warning btn-sm" />
    </form>
    <div>
        <a asp-controller="Productos" asp-action="ProductosEliminados" class="btn btn-secondary">Productos Eliminados</a>
    </div>
</div>





<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ListProductos.FirstOrDefault().Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ListProductos.FirstOrDefault().tipoProductos.Tipo)
            </th>
            <th style="text-align: right;">
                @Html.DisplayNameFor(model => model.ListProductos.FirstOrDefault().Precio)
            </th>
            @* <th> *@
            @*     @Html.DisplayNameFor(model => model.ListProductos.FirstOrDefault().Imagen) *@
            @* </th>             *@
            <th></th>
        </tr>
    </thead>
    <tbody>
            @if (Model.ListProductos != null && Model.ListProductos.Count > 0)
            {
                @foreach (var item in Model.ListProductos)
                {
                <tr>
                    <td>
                            @Html.DisplayFor(modelItem => item.Nombre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.tipoProductos.Tipo)
                    </td>
                    <td style="text-align: right">
                        $    @Html.DisplayFor(modelItem => item.Precio)
                    </td>
                    @* <td> *@
                    @*         @if (!string.IsNullOrEmpty(@item.Imagen)) *@
                    @*         { *@
                    @*         <img src="~/Imagenes/Productos/@item.Imagen" style="max-width:100px" /> *@
                    @*         } *@
                    @* </td> *@
                    <td style="text-align: center">
                        <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning">Editar</a> |
                        <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-warning">Detalles</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Borrar</a>
                    </td>
                </tr>
                }
            }
            else
            {
                <tr>
                    <td colspan="5">
                        <h4>No existen datos segun filtros</h4>
                    </td>
                </tr>
            }
    </tbody>
</table>

<script>
    document.addEventListener('keydown', function (event) {
        if (event.altKey && event.key === 'e') {
            event.preventDefault(); // Evita la acción predeterminada del navegador
            window.location.href = '@Url.Action("Create", "Productos")'; // Redirige al método Create del controlador Ventas
        }
    });
</script>

<partial name="_Paginador" for="@Model.paginadorVM" />

Mamma_Pasta/Views/Productos/ProductosEliminados.cshtml
@model List<Producto>

<h2>Productos Eliminados</h2>

<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Tipo</th>
            <th>Descripcion</th>
            <th>Precio</th>
            <th>Imagen</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var producto in Model)
        {
            <tr>
                <td>@producto.Id</td>
                <td>@producto.Nombre</td>
                <td>@producto.tipoProductos?.Tipo</td>
                <th>@producto.Descripcion</th>
                <td>@producto.Precio</td>
                <td>@producto.Imagen</td>
                <td>
                    <div class="d-flex gap-2">
                        <a asp-action="Details" asp-route-id="@producto.Id" class="btn btn-warning">Detalles</a> |
                        <form asp-action="RestaurarProducto" asp-route-id="@producto.Id" method="post">
                            <button type="submit" class="btn btn-success">Restaurar</button>
                        </form>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>
<div>
    <a asp-action="Index" class="btn btn-warning" style="margin-top:50px">Volver a la lista</a>
</div>