Mamma_Pasta/Models/Paginador.cs
namespace Mamma_Pasta.Models
{
    public class Paginador
    {
        public int paginaActual { get; set; }
        public int cantRegistros { get; set; }
        public int cantRegistrosPagina { get; set; }

        public int cantPaginas => (int)Math.Ceiling((decimal)cantRegistros / cantRegistrosPagina);

        public Dictionary<string, string> filtros { get; set; } = new Dictionary<string, string>();
    }
}

Mamma_Pasta/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Mamma_Pasta.Data;
using Mamma_Pasta.Models;
using Mamma_Pasta.Migrations;
using Microsoft.AspNetCore.Authorization;

namespace Mamma_Pasta.Controllers
{

    public class ClientesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ClientesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Clientes
        public async Task<IActionResult> Index()
        {
            var clientes = _context.Clientes
                .Include(c => c.TiposDePago)
                .Where(v => v.Activo)
                .AsQueryable();
            return View(clientes);
        }
        public async Task<IActionResult> ClientesEliminados()
        {
            var clientes = await _context.Clientes
                .Where(v => !v.Activo)
                .OrderBy(v => v.Nombre)
                .ToListAsync();

            return View(clientes);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RestaurarCliente(int id)
        {
            var cliente = await _context.Clientes.FindAsync(id);
            if (cliente == null)
            {
                return NotFound();
            }

            // Restaurar la venta cambiando Activo a true
            cliente.Activo = true;
            _context.Clientes.Update(cliente);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(ClientesEliminados));
        }

        // GET: Clientes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes
                .Include(c => c.TiposDePago)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // GET: Clientes/Create
        public IActionResult Create()
        {
            ViewData["TipoDePagoId"] = new SelectList(_context.TiposDePago, "Id", "Tipo");
            return View();
        }

        // POST: Clientes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Apellido,Telefono,Direccion,TipoDePagoId")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cliente);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["TipoDePagoId"] = new SelectList(_context.TiposDePago, "Id", "Tipo", cliente.TipoDePagoId);
            return View(cliente);
        }

        // GET: Clientes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes.FindAsync(id);
            if (cliente == null)
            {
                return NotFound();
            }
            ViewData["TipoDePagoId"] = new SelectList(_context.TiposDePago, "Id", "Tipo", cliente.TipoDePagoId);
            return View(cliente);
        }

        // POST: Clientes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Apellido,Telefono,Direccion,TipoDePagoId")] Cliente cliente)
        {
            if (id != cliente.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cliente);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClienteExists(cliente.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["TipoDePagoId"] = new SelectList(_context.TiposDePago, "Id", "Tipo", cliente.TipoDePagoId);
            return View(cliente);
        }

        // GET: Clientes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes
                .Include(c => c.TiposDePago)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // POST: Clientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cliente = await _context.Clientes.FindAsync(id);
            if (cliente == null)
            {
                return NotFound();
            }
            cliente.Activo = false;
            _context.Clientes.Update(cliente);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        private bool ClienteExists(int id)
        {
            return _context.Clientes.Any(e => e.Id == id);
        }
    }
}

Mamma_Pasta/Controllers/VentasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Mamma_Pasta.Data;
using Mamma_Pasta.Models;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Authorization;

namespace Mamma_Pasta.Controllers
{

    public class VentasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public VentasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Ventas
        public async Task<IActionResult> Index(DateTime? fechaDesde, DateTime? fechaHasta)
        {
            var ventas = _context.Ventas
                          .Include(v => v.RengVentas)
                          .Include(v => v.Clientes) // Incluir el cliente
                          .Where(v => v.Activo) // Filtrar solo ventas activas
                          .AsQueryable();

            // Aplicar filtro por fechas si están presentes
            if (fechaDesde.HasValue)
            {
                ventas = ventas.Where(v => v.Fecha >= fechaDesde.Value);
            }

            if (fechaHasta.HasValue)
            {
                ventas = ventas.Where(v => v.Fecha <= fechaHasta.Value);
            }

            ViewData["FechaDesde"] = fechaDesde?.ToString("yyyy-MM-dd");
            ViewData["FechaHasta"] = fechaHasta?.ToString("yyyy-MM-dd");
            // Ordenar por fecha descendente
            var listaVentas = await ventas.OrderByDescending(v => v.Fecha).ToListAsync();

            return View(listaVentas);
        }
        public async Task<IActionResult> VentasEliminadas()
        {
            var ventas = await _context.Ventas
                .Where(v => !v.Activo) // Filtrar solo las ventas eliminadas
                .Include(v => v.RengVentas)
                .Include(v => v.Clientes) // Incluir el cliente
                .OrderByDescending(v => v.Fecha)
                .ToListAsync();

            return View(ventas);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RestaurarVenta(int id)
        {
            var venta = await _context.Ventas.FindAsync(id);
            if (venta == null)
            {
                return NotFound();
            }

            // Restaurar la venta cambiando Activo a true
            venta.Activo = true;
            _context.Ventas.Update(venta);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(VentasEliminadas));
        }


        // GET: Ventas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var venta = await _context.Ventas
            .Include(v => v.RengVentas)
            .ThenInclude(r => r.Productos)
            .Include(v => v.Clientes) // Incluir el cliente
            .ThenInclude(c => c.TiposDePago) // Incluir el tipo de pago del cliente
            .FirstOrDefaultAsync(m => m.Id == id);

            if (venta == null)
            {
                return NotFound();
            }
            var vm = new vmVentas
            {
                Ventas = venta,
                RenglonesVentas = venta.RengVentas.ToList(),
                Clientes = venta.Clientes // Asignar cliente a la vista modelo
            };

            return View(vm);
        }

        // GET: Ventas/Create
        public IActionResult Create(int? tipoProductoId)
        {
            var vm = new vmVentas
            {
                Ventas = new Venta { Fecha = DateTime.Now },
                RenglonesVentas = new List<RenglonVenta> { new RenglonVenta() } // Inicializa un renglón vacío
            };

            // Lista de tipos de productos
            ViewBag.TiposProducto = _context.TiposProductos.ToList();

            // Cargar la lista de clientes disponibles
            ViewBag.Clientes = new SelectList(_context.Clientes, "Id", "Nombre");

            // Filtrar productos según el tipo seleccionado
            var productos = _context.Productos.AsQueryable();

            if (tipoProductoId.HasValue)
            {
                productos = productos.Where(p => p.TipoProductoId == tipoProductoId.Value);
            }


            // Pasa la lista de productos al ViewBag para poder mostrarlos en la vista con filtrado
            ViewBag.Productos = productos.Select(p => new
            {
                p.Id,
                p.Nombre,
                p.Precio
            }).ToList();

            
            // Mantener el tipo seleccionado en la vista
            ViewBag.TipoSeleccionado = tipoProductoId;
            
            return View(vm);
        }

        // POST: Ventas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(vmVentas vm, string productosSeleccionados)
        {
            if (ModelState.IsValid)
            {
                // Mostrar los datos recibidos en la consola para debug
                Console.WriteLine("Datos recibidos: " + productosSeleccionados);

                if (!string.IsNullOrEmpty(productosSeleccionados))
                {
                    var renglones = JsonConvert.DeserializeObject<List<RenglonVenta>>(productosSeleccionados);

                    if (renglones != null && renglones.Any())
                    {
                        // Obtener el cliente desde la base de datos
                        var cliente = await _context.Clientes.FindAsync(vm.clienteId);
                        if (cliente == null)
                        {
                            ModelState.AddModelError("", "El cliente seleccionado no es válido.");
                            return View(vm);
                        }

                        // Crear la venta con sus renglones
                        var venta = new Venta
                        {
                            Fecha = vm.Ventas.Fecha,                           
                            Total = renglones.Sum(r => r.Subtotal),
                            ClienteId = vm.clienteId,  // Asociar ClienteId
                            Clientes = cliente,         // Asociar el objeto Cliente
                            RengVentas = renglones.Select(r => new RenglonVenta
                            {
                                ProductoId = r.Id, // Asegúrate de que se asigna correctamente el ID del producto
                                Cantidad = r.Cantidad,
                                Precio = r.Precio,
                                Subtotal = r.Subtotal,
                                Productos = _context.Productos.FirstOrDefault(p => p.Id == r.Id), // Cargar el producto asociado                          
                            }).ToList()
                        };

                        _context.Ventas.Add(venta);
                        await _context.SaveChangesAsync();
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        ModelState.AddModelError("", "No se recibieron productos en la venta.");
                    }
                }
            }


            ViewBag.Productos = _context.Productos.ToList();
            ViewData["IdProducto"] = new SelectList(_context.Productos, "Id", "Nombre", vm.Productos?.Id);
            ViewData["ClienteId"] = new SelectList(_context.Clientes, "Id", "Nombre", vm.clienteId);
            return View(vm);
        }

        // GET: Ventas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var venta = await _context.Ventas.FindAsync(id);
            if (venta == null)
            {
                return NotFound();
            }

            var renglones = await _context.renglonesVentas
                                  .Where(r => r.VentaId == id)
                                  .ToListAsync();

            // Construir el modelo de vista `vmVentas`
            var vm = new vmVentas
            {
                Ventas = venta,
                RenglonesVentas = renglones
            };

            // Pasar la lista de productos al ViewBag (si es necesario para un dropdown en la vista)
            ViewBag.Productos = await _context.Productos.ToListAsync();
            ViewData["IdProducto"] = new SelectList(_context.Productos, "Id", "Nombre");
            return View(vm);
        }

        // POST: Ventas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, vmVentas vm)
        {
            if (id != vm.Ventas.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vm.Ventas);
                    foreach (var renglon in vm.RenglonesVentas)
                    {
                        if (renglon.Id == 0)
                        {
                            // Si el Id es 0, es un nuevo renglón, así que lo agregamos
                            _context.renglonesVentas.Add(renglon);
                        }
                        else
                        {
                            // Si el Id existe, actualizamos el renglón
                            _context.renglonesVentas.Update(renglon);

Mamma_Pasta/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mamma_Pasta</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Mamma_Pasta.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-warning border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="/Imagenes/Icons/logo_mamma_pasta.png" alt="MammaPasta" width="45" height="50"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Productos" asp-action="Index">Productos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ventas" asp-action="Index">Ventas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Clientes" asp-action="Index">Clientes</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Mamma_Pasta - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Mamma_Pasta/Views/Shared/_Paginador.cshtml
@model Mamma_Pasta.Models.Paginador

<nav aria-label="...">
    <ul class="pagination justify-content-center">
        @if (Model.paginaActual > 1)
        {
            <li class="page-item">
                <a class="page-link" asp-all-route-data="@Model.filtros" asp-route-pagina="1" tabindex="-1" aria-disabled="true">&laquo;</a>
            </li>
        }
        <li class="page-item @(Model.paginaActual > 1 ? "" : "disabled")">
            <a class="page-link" asp-all-route-data="@Model.filtros" asp-route-pagina="@(Model.paginaActual-1)" tabindex="-1" aria-disabled="true">&lt;</a>
        </li>
        @if(Model.paginaActual > 1)
        {
            <li class="page-item @(Model.paginaActual > 1 ? "" : "disabled")">
                <a class="page-link" asp-all-route-data="@Model.filtros" asp-route-pagina="@(Model.paginaActual-1)" tabindex="-1" aria-disabled="true">@(Model.paginaActual - 1)</a>
            </li>
        }
        
        <li class="page-item active" aria-current="page">
            <a class="page-link bg-warning">@Model.paginaActual</a>
        </li>
        <li class="page-item @(Model.paginaActual == Model.cantPaginas ? "disabled" : "")">
            <a class="page-link" asp-all-route-data="@Model.filtros" asp-route-pagina="@(Model.paginaActual+1)">@(Model.paginaActual+1)</a>
        </li>
        <li class="page-item @(Model.paginaActual == Model.cantPaginas ? "disabled" : "")">
            <a class="page-link" asp-all-route-data="@Model.filtros" asp-route-pagina="@(Model.paginaActual+1)">&gt;</a>
        </li>
        @if (Model.paginaActual != Model.cantPaginas)
        {
            <li class="page-item">
                <a class="page-link" asp-all-route-data="@Model.filtros" asp-route-pagina="@Model.cantPaginas" aria-disabled="true">&raquo (@Model.cantPaginas)</a>
            </li>
        }
    </ul>
    Cantidad de productos: @Model.cantRegistros
</nav>